# Generated by Django 4.2.3 on 2023-07-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Phone Screening', 'Phone Screening'), ('Interview', 'Interview'), ('2nd Interview', '2nd Interview'), ('3rd Interview', '3rd Interview'), ('Rejected Offer', 'Rejected Offer'), ('Accepted Offer', 'Accepted Offer')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
